rpcv05 update errors
NethermindEth/starknet.go pull request #422
Opened 2023-10-11 09:30 UTC by rianhughes

closes https://github.com/NethermindEth/starknet.go/issues/408

2023-10-12 05:39 UTC, cicr99 reviewed
The tasks on #408 are yet to be completed

2023-10-12 07:48 UTC, rianhughes commented
One task on #408 has to do with updating the errors, and the other has to do with updating a method. I might split updating the method into a separate pr if that's okay with you

2023-10-13 13:15 UTC, cicr99 commented
> One task on #408 has to do with updating the errors, and the other has to do with updating a method. I might split updating the method into a separate pr if that's okay with you #427

Ok, I agree that you can handle the update of the method separately. I updated the issue to track that task with #427  issue. On the other hand, there is the data field in CONTRACT_ERROR task, I left a comment there about it. In any case, I'll update your description to only reference issue #408, because the way it is will close the issue as soon as this get merged and I would like all the tasks to be finished before closing it.

2023-10-20 13:56 UTC, cicr99 approved these changes

2023-10-20 13:58 UTC, cicr99 requested changes

2023-10-20 13:58 UTC, cicr99 commented on rpc/errors.go
> +		message: "Invalid block hash",
I don't think this message needed to be changed  https://github.com/starkware-libs/starknet-specs/blob/c0980ed9aa5a8eb2def8d9b145fba27b4e29b7f9/api/starknet_api_openrpc.json#L3345

2023-10-24 13:25 UTC, cicr99 commented on rpc/errors.go
> +		message: "Invalid block hash",
I looked a bit more into it. It appears there is an inconsistency on the spec. BLOCK_NOT_FOUND error is defined twice with different error messages: [here](https://github.com/starkware-libs/starknet-specs/blob/c0980ed9aa5a8eb2def8d9b145fba27b4e29b7f9/api/starknet_api_openrpc.json#L3345) and [here](https://github.com/starkware-libs/starknet-specs/blob/c0980ed9aa5a8eb2def8d9b145fba27b4e29b7f9/api/starknet_trace_api_openrpc.json#L483C14-L483C29). "Block not found" seems like the correct message.

2023-10-24 13:26 UTC, closed without merging