Eventexample
NethermindEth/starknet.go pull request #593
Opened 2024-07-11 13:05 UTC by alex-sumner

Example code for reading event logs, as called for in issue https://github.com/NethermindEth/starknet.go/issues/578

2024-07-16 13:49 UTC, thiagodeev requested changes
Hi @alex-sumner, sorry for the delay.
Great job, thank you! Left some comments

2024-07-16 13:49 UTC, thiagodeev commented on examples/readEvents/README.md
> +1. Uncomment, and assign your Ethereum mainnet endpoint to the `RPC_PROVIDER_URL` variable in the ".env" file
Let's change "Ethereum" to "Starknet".
Also, could you change this example to use a testnet smart contract? It'll be smoother for the user to use only one RPC provider for all their example interactions without the need to change it.

2024-07-16 13:49 UTC, thiagodeev commented on examples/readEvents/main.go
> +		FromBlock: rpc.BlockID{Number: fromBlock},
We can change it to use the `rpc.WithBlockNumber` function, that way we don't need the FROM/TO_BLOCK variables

2024-07-16 13:49 UTC, thiagodeev commented on examples/readEvents/main.go
> +	events = readEvents(eventsInput, provider)
Your code is great, but we can make things simpler for new users. What about the first thing we do is call a single event using only starknet.go functions and basic types and print out that event info?
After this first part, we continue to show a more complex interaction (involving multiple calls, pagination, loops...).
Let's use the "readEvents" and "buildKeyFilter" only in this second part

2024-07-16 13:52 UTC, thiagodeev commented
Also, could you change these READMEs to include this example?
https://github.com/NethermindEth/starknet.go/blob/main/examples/README.md
https://github.com/NethermindEth/starknet.go/blob/main/README.md#run-examples

2024-10-02 14:51 UTC, thiagodeev commented
Hi @alex-sumner. Are you still available?

2024-10-02 15:02 UTC, alex-sumner commented
Hi yes I amOn 2 Oct 2024, at 15:51, Thiago Ribeiro ***@***.***> wrote:﻿
Hi @alex-sumner. Are you still available?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-02 15:28 UTC, thiagodeev commented
Could you please make the changes I mentioned?

2024-10-02 15:56 UTC, alex-sumner commented
Yes, I willOn 2 Oct 2024, at 16:28, Thiago Ribeiro ***@***.***> wrote:﻿
Could you please make the changes I mentioned?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-10 15:50 UTC, alex-sumner commented
Hi, I have pushed all the requested changes on my branch.

2025-01-14 12:01 UTC, alex-sumner commented
Hi,

How's it going? I made all the requested changes on 10 November for
https://github.com/NethermindEth/starknet.go/pull/593

Can this be merged?

Thanks,
Alex

On Wed, 2 Oct 2024 at 16:28, Thiago Ribeiro ***@***.***>
wrote:

> Could you please make the changes I mentioned?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NethermindEth/starknet.go/pull/593#issuecomment-2388973506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALA3NDFY57PDBSOCLSNVY6LZZQGJ5AVCNFSM6AAAAABKW6KFU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBYHE3TGNJQGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-16 13:45 UTC, thiagodeev commented
Hi @alex-sumner. Sorry for the delay.
We are really focused on RPCv0.8.0, that's why I still haven't reviewed your PR and others.
I'll do it ASAP when I finish RPCv08. Sorry for that

2025-01-16 14:42 UTC, alex-sumner commented
Ok, thanksOn 16 Jan 2025, at 13:45, Thiago Ribeiro ***@***.***> wrote:﻿
Hi @alex-sumner. Sorry for the delay.
We are really focused on RPCv0.8.0, that's why I still haven't reviewed your PR and others.
I'll do it ASAP when I finish RPCv08. Sorry for that

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-04-11 16:11 UTC, thiagodeev approved these changes

2025-04-11 16:18 UTC, thiagodeev commented
Thanks @alex-sumner, and sorry for the delay!
I've upgraded the examples, adding more example cases and descriptions.

2025-04-11 16:19 UTC, merged